kind: pipeline
type: docker
name: deploy
workspace:
  base: go
  path: src/redissyncer-portal
steps:
  - name: build
    image: golang
    network_mode: host
    commands:
      # - go mod tidy
      #- go mod vendor
      - export https_proxy=http://127.0.0.1:1081
      - export http_proxy=http://127.0.0.1:1081
      - export all_proxy=socks5://127.0.0.1:1080
      - curl https://www.facebook.com
      - go build -o redissyncer-portal
    environment:
      GO111MODULE: on
      GOPROXY: https://goproxy.cn

  - name: stopserver
    image: appleboy/drone-ssh
    settings:
      host:
        - 10.0.0.21
        - 10.0.0.22
        - 10.0.0.23
      username: root
      key_path: ./id_rsa
      script:
        - /root/redissyncer-portal/redissyncer-portal stop

  - name: publish
    image: appleboy/drone-scp
    settings:
      host:
        - 10.0.0.21
        - 10.0.0.22
        - 10.0.0.23
      user: root
      port: 22
      password: Git785230
      target: /root/redissyncer-portal
      source: redissyncer-portal

  - name: startserver
    image: appleboy/drone-ssh
    settings:
      host:
        - 10.0.0.21
        - 10.0.0.22
        - 10.0.0.23
      username: root
      key_path: ./id_rsa
      script:
        - /root/redissyncer-portal/redissyncer-portal start -d



