---
kind: pipeline
type: docker
name: deploy

platform:
  os: linux
  arch: amd64

#workspace:
#  base: go
#  path: src/redissyncer-portal
clone:
  disable: true

steps:
  - name: clone
    image: alpine/git
    commands:
      - export https_proxy=http://10.0.0.101:1081
      - export http_proxy=http://10.0.0.101:1081
      - export all_proxy=socks5://10.0.0.101:1080
      - git clone https://github.com/jiashiwen/redissyncer-portal.git .


  - name: build
    image: golang
    commands:
      - export https_proxy=http://10.0.0.101:1081
      - export http_proxy=http://10.0.0.101:1081
      - export all_proxy=socks5://10.0.0.101:1080
      - curl https://www.google.com
      - go build -o redissyncer-portal
    environment:
      GO111MODULE: on
  #      GOPROXY: https://goproxy.cn

  - name: stopserver
    image: appleboy/drone-ssh
    settings:
      host:
        - 10.0.0.21
        - 10.0.0.22
        - 10.0.0.23
      key_path: ./id_rsa
      script:
        - /root/redissyncer-portal/redissyncer-portal stop
      username: root

  - name: publish
    image: appleboy/drone-scp
    settings:
      host:
        - 10.0.0.21
        - 10.0.0.22
        - 10.0.0.23
      password: Git785230
      port: 22
      source: redissyncer-portal
      target: /root/redissyncer-portal
      user: root

  - name: startserver
    image: appleboy/drone-ssh
    settings:
      host:
        - 10.0.0.21
        - 10.0.0.22
        - 10.0.0.23
      key_path: ./id_rsa
      script:
        - /root/redissyncer-portal/redissyncer-portal start -d
      username: root

...
